apiVersion: v1
kind: Service
metadata:
  name: citas-medicas-service
spec:
  selector:
    app: citas-medicas
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: LoadBalancer
